# .github/workflows/render-rmarkdown.yml
name: Render R Markdown Workflows

on:
  schedule:
    - cron: '0 0 * * *'          # daily at 00:00 UTC
  workflow_dispatch:             # manual trigger

# 0. GITHUB_TOKEN にリポジトリ書き込み権限を付与
permissions:
  contents: write

jobs:
  run_r_code:
    runs-on: ubuntu-latest

    steps:
      # 1. Check out the repo (フル履歴取得)
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 2. Set up R
      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: 'release'

      # 3. Install OS libraries (incl. Harfbuzz/Fribidi for textshaping → tidyverse)
      - name: Install system libraries
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            pandoc \
            libxml2-dev libicu-dev libssl-dev libcurl4-openssl-dev \
            libfontconfig1-dev libfreetype6-dev libpng-dev libjpeg-dev libtiff5-dev \
            libharfbuzz-dev libfribidi-dev

      # 4. (Optional) cache your private package library for speed
      - name: Cache R packages
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}/Rlibrary
          key: ${{ runner.os }}-rlibs-${{ hashFiles('**/*.Rmd') }}

      # 5. Create a per‑workflow R library and install needed R packages
      - name: Install R packages
        env:
          R_LIBS_USER: ${{ github.workspace }}/Rlibrary
        run: |
          mkdir -p "$R_LIBS_USER"
          Rscript -e 'install.packages(
            c("rmarkdown","tidyverse","rvest","lubridate"),
            repos="https://cloud.r-project.org",
            dependencies=TRUE
          )'

      # 6. Render initial processing once
      - name: Render initial processing (first run only)
        env:
          R_LIBS_USER: ${{ github.workspace }}/Rlibrary
        run: |
          if [ ! -f initialized.lock ]; then
            Rscript -e "rmarkdown::render('initial_processing.Rmd')"
            touch initialized.lock
          else
            echo "Initial processing already completed."
          fi

      # 7. Render daily task
      - name: Render daily task
        env:
          R_LIBS_USER: ${{ github.workspace }}/Rlibrary
        run: |
          Rscript -e "rmarkdown::render('daily_task.Rmd')"

      # 8. Commit & push generated CSVs back to repository
      - name: Commit and push CSVs
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data-全国.csv data-東京都.csv data-その他.csv merged_data/merged_data.csv
          git diff --quiet || git commit -m "Update disease CSV outputs"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
