name: Run R Markdown Workflows

on:
  schedule:
    - cron: '0 0 * * *'      # daily 00:00 UTC
  workflow_dispatch:

jobs:
  run_r_code:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install Linux libraries required by R packages
        uses: r-lib/actions/setup-system-dependencies@v2
        with:
          extra-packages: |
            pandoc
            libharfbuzz-dev
            libfribidi-dev

      - name: Install required R packages (cached)
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            rmarkdown
            tidyverse
            rvest
            lubridate

      - name: Render initial processing (first run only)
        run: |
          if [ ! -f initialized.lock ]; then
            Rscript -e "rmarkdown::render('initial_processing.Rmd')"
            touch initialized.lock
          else
            echo "Initial processing already completed."
          fi

      - name: Render daily task
        run: Rscript -e "rmarkdown::render('daily_task.Rmd')"
