name: Run R Markdown Workflows

on:
  schedule:
    - cron: '0 0 * * *'   # 毎日UTCの0:00に実行
  workflow_dispatch:       # GitHubの画面から手動実行も可能

jobs:
  run_r_code:
    runs-on: ubuntu-latest
    steps:
      # 1. リポジトリの最新内容を取得する
      - name: Checkout repository
        uses: actions/checkout@v2

      # 2. R の環境をセットアップする
      - name: Setup R
        uses: r-lib/actions/setup-r@v2

      # 3. 必要なシステムライブラリをインストール
      #    rvest や tidyverse のビルドには libxml2-dev、libicu-dev、libssl-dev、libcurl4-openssl-dev などが必要です
      - name: Install system libraries
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc libxml2-dev libicu-dev libssl-dev libcurl4-openssl-dev

      # 4. パッケージをインストールするためのユーザーライブラリ用のフォルダを作成
      - name: Create R library directory
        run: mkdir -p ${{ github.workspace }}/Rlibrary

      # 5. 必要な R パッケージをユーザーライブラリにインストール
      - name: Install required R packages
        env:
          R_LIBS_USER: ${{ github.workspace }}/Rlibrary
        run: |
          Rscript -e 'install.packages(c("rmarkdown", "tidyverse", "rvest", "lubridate"), dependencies = TRUE, repos = "https://cloud.r-project.org")'

      # 6. 【デバッグ用】インストールしたパッケージが正しく読み込めるか確認する
      - name: Verify installed packages
        env:
          R_LIBS_USER: ${{ github.workspace }}/Rlibrary
        run: |
          Rscript -e 'library(tidyverse); library(rvest); library(lubridate); print("Packages loaded successfully")'

      # 7. 初期処理（initial_processing.Rmd）を初回のみ実行する
      - name: Render initial processing (if not already run)
        env:
          R_LIBS_USER: ${{ github.workspace }}/Rlibrary
        run: |
          if [ ! -f initialized.lock ]; then
            Rscript -e "rmarkdown::render('initial_processing.Rmd')"
            touch initialized.lock
          else
            echo 'Initial processing already completed.'
          fi

      # 8. 毎日実行するタスク（daily_task.Rmd）を実行する
      - name: Render daily task
        env:
          R_LIBS_USER: ${{ github.workspace }}/Rlibrary
        run: |
          Rscript -e "rmarkdown::render('daily_task.Rmd')"
