name: Run R Markdown Workflows

# どんなタイミングでこのワークフローを実行するかを指定
on:
  # 毎日UTCの0:00に実行する設定です
  schedule:
    - cron: '0 0 * * *'
  # GitHubの画面から手動で実行することも可能にします
  workflow_dispatch:

jobs:
  run_r_code:
    # このジョブは最新のUbuntu環境（サーバー）で実行されます
    runs-on: ubuntu-latest

    steps:
      # 1. GitHubリポジトリの内容をチェックアウト（コピー）する
      - name: Checkout repository
        uses: actions/checkout@v2

      # 2. Rの環境をセットアップする（Rが使えるようになる）
      - name: Setup R
        uses: r-lib/actions/setup-r@v2

      # 3. R Markdownを実行するために必要なパッケージ（ここではrmarkdown）をインストールする
      - name: Install required R packages
        run: |
          Rscript -e 'install.packages("rmarkdown", repos="https://cran.r-project.org")'

      # 4. 毎日実行する処理が書かれたR Markdownファイル（daily_task.Rmd）を実行する
      - name: Render daily R Markdown file
        run: |
          Rscript -e "rmarkdown::render('daily_task.Rmd')"

      # 5. 初回のみ実行する処理が書かれたR Markdownファイル（initialize_once.Rmd）を条件付きで実行する
      - name: Render initialization R Markdown (only if not already run)
        run: |
          # 初回の実行かどうか確認するためのチェック
          if [ ! -f initialized.lock ]; then
            Rscript -e "rmarkdown::render('initialize_once.Rmd')"
            # 実行後にロックファイルを作成して、初回実行済みとマークする
            touch initialized.lock
          else
            echo 'Initialization already completed.'
          fi
