# .github/workflows/render-rmarkdown.yml
name: Render R Markdown Workflows

on:
  schedule:
    - cron: '0 0 * * *'          # run daily at 00:00 UTC
  workflow_dispatch:             # allow manual trigger

jobs:
  render_rmd:
    runs-on: ubuntu-latest
    permissions:
      contents: read             # enough for actions/checkout

    steps:
      # 1 – Check out repository
      - name: Check out repository
        uses: actions/checkout@v4

      # 2 – Set up R (defaults to latest release)
      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: 'release'   # pin a specific version if you wish

      # 3 – Install R *and* Linux dependencies (cached)
      #     pak figures out the correct system libraries such as
      #     libharfbuzz-dev and libfribidi-dev that tidyverse needs.
      - name: Install R & system dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: |
            any::rmarkdown
            any::tidyverse
            any::rvest
            any::lubridate
          cache: true            # speeds up subsequent runs

      # 4 – Render the “first‑run” Rmd once
      - name: Render initial processing (first run only)
        run: |
          if [ ! -f initialized.lock ]; then
            Rscript -e "rmarkdown::render('initial_processing.Rmd')"
            touch initialized.lock
          else
            echo "Initial processing already completed."
          fi

      # 5 – Render the daily task
      - name: Render daily task
        run: Rscript -e "rmarkdown::render('daily_task.Rmd')"
