name: Run R Markdown Workflows

on:
  schedule:
    - cron: '0 0 * * *'   # 毎日UTCの0:00に実行
  workflow_dispatch:

jobs:
  run_r_code:
    runs-on: ubuntu-latest
    steps:
      # 1. リポジトリの内容をチェックアウト
      - name: Checkout repository
        uses: actions/checkout@v2

      # 2. R の環境をセットアップ
      - name: Setup R
        uses: r-lib/actions/setup-r@v2

      # 3. 必要なシステムライブラリをインストール
      # ※ rvest や tidyverse のビルドには libxml2-dev, libicu-dev, libssl-dev, libcurl4-openssl-dev 等が必要となる
      - name: Install system libraries
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc libxml2-dev libicu-dev libssl-dev libcurl4-openssl-dev

      # 4. 必要な R パッケージをインストール (dependencies=TRUE を指定)
      - name: Install required R packages
        run: |
          Rscript -e 'install.packages(c("rmarkdown", "tidyverse", "rvest", "lubridate"), dependencies = TRUE, repos = "https://cran.r-project.org")'

      # 4.1. 【デバッグ用】パッケージがちゃんとインストールされているか確認する
      #- name: Verify installed R packages
      #  run: |
      #    Rscript -e 'library(tidyverse); library(rvest); library(lubridate); sessionInfo()'

      # 5. 初回のみ実行する初期処理 (初回なら実行、以降はスキップ)
      - name: Render initial processing (if not already run)
        run: |
          if [ ! -f initialized.lock ]; then
            Rscript -e "rmarkdown::render('initial_processing.Rmd')"
            touch initialized.lock
          else
            echo 'Initial processing already completed.'
          fi

      # 6. 毎日実行するタスクの実行
      - name: Render daily task
        run: |
          Rscript -e "rmarkdown::render('daily_task.Rmd')"
